name: Dev → Main CI

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    name: Backend Build & Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci --include=dev

      - name: Lint & Format
        working-directory: ./backend
        run: |
          npx eslint . --ext .ts
          npx prettier --write .

      - name: Build backend
        working-directory: ./backend
        run: npm run build

      # Если есть тесты, их можно включить
      # - name: Run tests
      #   working-directory: ./backend
      #   run: npm test

  build-frontend:
    name: Frontend Build & Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci --include=dev

      - name: Lint & Format
        working-directory: ./frontend
        run: |
          npx eslint . --ext .ts
          npx prettier --write .

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build